
FROM alpine:3.7

## Install PHP for Laravel
RUN addgroup -g 82 -S www-data \
 && adduser -h /var/www -g www-data -s /sbin/nologin -G www-data -SDH -u 82 www-data \
 && apk add --no-cache \
    php7 \
    php7-ctype \
    php7-dom \
    php7-json \
    php7-mbstring \
    php7-openssl \
    php7-pdo \
    php7-pdo_sqlite \
    php7-phar \
    php7-session \
    php7-tokenizer \
    php7-xml \
    php7-xdebug \
    php7-zlib

## Install Composer for Laravel
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 && if [ $(wget -O - https://composer.github.io/installer.sig 2>/dev/null) != $(php -r "echo hash_file('SHA384', 'composer-setup.php');") ]; then \
      echo 'ERROR: Invalid installer signature'; exit 1 \
    ;fi \
 && php composer-setup.php --install-dir=/usr/local/bin --filename=composer

## Create Laravel Project
RUN composer create-project --prefer-dist laravel/laravel TheTest "5.5.*"

## Setup Working Directory
WORKDIR /TheTest

## Migration database
COPY files/.env /TheTest/
RUN touch /TheTest/database/database.sqlite \
 && php /TheTest/artisan migrate

## Create Dummy 50000 rows
COPY files/DatabaseSeeder.php /TheTest/database/seeds/
RUN php /TheTest/artisan db:seed

## Setup Test Code
COPY files/TestCode.php /TheTest/app/Console/Commands/
CMD [ "php", "artisan", "test" ]
